apiVersion: v1
kind: Service
metadata:
  name: register-app-service
  labels:
    app: register-app 
spec:
  selector:
    app: register-app

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 30050
  type: NodePort
